# Generated by Django 4.2.30 on 2026-09-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, help_text='Upload MP3 format track file', null=True, upload_to='songs/audio/')),
                ('cover_art', models.ImageField(blank=True, help_text='Upload 1:1 ratio square artwork file', null=True, upload_to='songs/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
